### ISSUE TITLE
Additional feature

### ISSUE THREAD

**Issue by jgilgan** [OpenPanzerProject/TankIR#1]
Hello!
A nice additional Feature to this project would be the addition of a servo controlled gun traverse with optional speed control.
So you could pan the artillery slowly and fire it with your rc controller.

**Comment by OpenPanzerProject** [comment]
Response left in the RC Tank Warfare thread where this question was originally posed: [CLICK HERE](https://www.rctankwarfare.co.uk/forums/viewtopic.php?p=231846#p231846)
